### ISSUE TITLE
it gave me the exception message until I add the folder name to tinted.json location in `me.manabreak.ratio.ui.Res.java`

### ISSUE THREAD

**Issue by christinazou** [manabreak/ratio#12]
I have run the source code on mac.
it gave me the exception message until I add the folder name to tinted.json location in `me.manabreak.ratio.ui.Res.java`

:
> Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error reading file: tinted.json
> 	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:98)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:75)
> 	at com.kotcrab.vis.ui.VisUI.load(VisUI.java:87)
> 	at me.manabreak.ratio.ui.Res.load(Res.java:30)
> 	at me.manabreak.ratio.EditorGame.create(EditorGame.java:32)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
> Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: tinted.json
> 	at com.badlogic.gdx.utils.Json.fromJson(Json.java:711)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:96)
> 	... 6 more
> Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing file: tinted.json
> 	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:78)
> 	at com.badlogic.gdx.utils.Json.fromJson(Json.java:709)
> 	... 7 more
> Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: tinted.json (Internal)
> 	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
> 	at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
> 	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:76)
> 	... 8 more

from
```
 public static void load() {
        VisUI.load(Gdx.files.internal("tinted.json"));
    }
```
to
```
    public static void load() {
        VisUI.load(Gdx.files.internal("editor/assets/tinted.json"));
    }
```

**Comment by manabreak** [comment]
A better approach is to set your working directory to `editor/assets`. This way your local builds will still work as intended; hard-coding the path will break JAR builds.

This folder structure actually comes from LibGDX's way of doing this, which Ratio is built with. :)

**Comment by christinazou** [comment]
got it. Thank you
